api_platform:
  title: "Universe-Api"
  version: "v0.1"
  mapping:
    paths: ['%kernel.project_dir%/src/Entity']
  openapi:
    contact:
      name: "Universe-Api"
      url: 'https://'
  patch_formats:
    json: ['application/merge-patch+json']
  swagger:
    versions: [3]
  show_webby: false
  defaults:
    normalization_context:
      skip_null_values: false
    paginationEnabled: true
    pagination_client_items_per_page: true
    pagination_items_per_page: 25
  enable_swagger_ui: true
  enable_re_doc: true
  #allow_plain_identifiers: true

  collection:
    order_parameter_name: 'order'
    pagination:
      enabled_parameter_name: page
      items_per_page_parameter_name: size